### PR TITLE
Return camera's ids when syncing with backend

### PR DESCRIPTION
**Pull request by lucabenvenuto**

### CODE REVIEW

**Review by renzodgc — APPROVED** [review]
:raised_hands:

**Review by pgrill — COMMENTED** [review]
We should create this PR against the neauralet repository.

**Review by mats-claassen — APPROVED** [review]

**Comment by chaba11** [comment]
On line 85, the status code should be HTTP_200_OK, as the answer from the backend is not 204 anymore.

**Review by chaba11 — CHANGES_REQUESTED** [review]
@lucabenvenuto On line 85, the status code should be HTTP_200_OK, as the answer from the backend is not 204 anymore.

**Review by chaba11 — APPROVED** [review]

**Pull request closed without merging**
